### PR TITLE
Added BSDataTable Component

### PR DESCRIPTION
**Pull request by MasterSkriptor**
This is the beginning of the data templates we discussed in #283. It has been added to a new class library in the solution.

The table page of the site has been updated with examples of using the data table component.  You will notice that the component utilizes all of the attributes of its relative component BSTable.

Please let me know if you have any suggestions, or if this will suffice in terms of adding more data templated components.

### CODE REVIEW

**Comment by MasterSkriptor** [comment]
I'll get it done.

**Comment by MasterSkriptor** [comment]
I moved the component to the BlazorStrap.Extensions namespace. I also cleaned up the mess I had made of the folder structure. I moved the BSTable component into the src directory, and changed its name to BlazorStrap.Extensions.BSDataTable. I did the same with the project name.

Hopefully I understood the request correctly. I also apologize for not picking up on that in the first place, it makes sense.

**Comment by MasterSkriptor** [comment]
I am currently working on a new Data Template for the carousel. Which is one I would like to implement in a project I am working on. So, if it is agreeable to @chanan and @jbomhold3 I would like to make a project called BlazorStrap.Extensions.DataComponents, and add the data components into there with a namespace of BlazorStrap.Extensions.DataComponents. From there I can use the same folder structure as the original BlazorStrap, which will make things easier to follow.

As for BSDataTable, I will add it into the project in a future pull request If that is okay.

**Comment by chanan** [comment]
Makes sense to me, @jbomhold3 ?

**Comment by jbomhold3** [comment]
Works for me

**Comment by jbomhold3** [comment]
This one safe to merge? Or will you be adding to it?

**Comment by chanan** [comment]
You can merge it. I will check it out tomorrow either on a branch or master. Doesn’t matter.

**Pull request merged**
