### PR TITLE
Added 4 new options on bootstrap modal component. IsFullWidth, IsBottom, IsFullHeight and IsFullScreen.

### PR DESCRIPTION
**Pull request by arivera12**
Added 4 new options on bootstrap modal components. IsFullWidth for a full width modal, IsBottom to place modal at the bottom of the screen, IsFullHeight to place modal on the full height of the screen, IsFullScreen for a full screen window. You can have a bottom sheet like modal using the combined options of IsFullWidth and IsBottom. Modal examples pages have been updated with this changes as well.

### Full Width Modal
image

### Bottom Modal
image

### Bottom Sheet like Modal
image

### Full Height Modal
image

### Full Screen Modal
image

### CODE REVIEW

**Comment by chanan** [comment]
Thanks! I will merge it later tonight!

**Comment by arivera12** [comment]
Keep me in the loop please.

**Comment by arivera12** [comment]
@chanan I added screenshots.

**Comment by chanan** [comment]
@arivera12 Finishing up my "real" work for the day, and will be merging this and publishing shortly

**Comment by arivera12** [comment]
Don't worry :)

**Pull request merged**
