### PR TITLE
DropDownManager changes.

### PR DESCRIPTION
**Pull request by jbomhold3**
This update removes the requirement for ID. The basic setup is now.
```
<NavItem IsDropdown="true">
    <DropdownToggle Color="Color.Light">Dropdown link</DropdownToggle>
    <DropdownMenu>
        <DropdownItem Href="#">Action</DropdownItem>
    </DropdownMenu>
</NavItem>
```

Added Support for Normal Dropdowns and split button.
```
<Dropdown>
        <DropdownToggle>Dropdown</DropdownToggle>
        <DropdownMenu>
            <DropdownItem Href="#">Action</DropdownItem>
            <DropdownItem Href="#">Another Action</DropdownItem>
            <DropdownItem Href="#">Yet Another Action</DropdownItem>
        </DropdownMenu>
</Dropdown>

<Dropdown>
        <ButtonGroup>
            <BlazorButton Color="Color.Secondary">Action</BlazorButton>
            <DropdownToggle IsSplit="true" Color="Color.Secondary" />
            <DropdownMenu>
                <DropdownItem Href="#">Action</DropdownItem>
                <DropdownItem Href="#">Another Action</DropdownItem>
                <DropdownItem IsDivider="true" />
                <DropdownItem Href="#">Yet Another Action</DropdownItem>
            </DropdownMenu>
        </ButtonGroup>
    </Dropdown>
```
I have started to adjust the sample pages to test everything. I got to sizing on dropdowns.razor. The snappets still need updated.

### CODE REVIEW

**Comment by jbomhold3** [comment]
Two other commits are to auto close the menu on different events. 
83f8db8 is strictly a workaround to missing Blazor events. It watches for mouse out. Sets a timer. If mouseover is called the timer pauses. So its effectively doing this.  Exit parent -> StartTime-> Enter child StopTimer -> Exit child start timer. At the moment it's a one-second timer probably overkill on time but It closes fast enough for my liking.

**Comment by jbomhold3** [comment]
7e3d867 Moves the interop in Model.razor to OnAfterRender. This was done to correct a prerendering bug. Sorry about all the commits in one PR. Actively using it and addressing things as I find them.

**Comment by chanan** [comment]
Let me know when you are ready to merge this

**Comment by jbomhold3** [comment]
Should be good to go

**Comment by jbomhold3** [comment]
Good to Go

**Pull request merged**
