### PR TITLE
Mocked up BSDataTableRow concept

### PR DESCRIPTION
**Pull request by zandermar18**
Created an MVP for the general concept of the feature. It can be seen in action in the docs project. Relates to issue #490

### CODE REVIEW

**Comment by zandermar18** [comment]
Realized that it would be better to just inherit from BSTR but the concept is the same.

**Review by jbomhold3 — APPROVED** [review]
Looks good will need to test before fully merging.

**Comment by zandermar18** [comment]
Sounds good, let me rewrite it to inherit from `BSTR` and I'll resubmit

**Comment by zandermar18** [comment]
Modified to inherit from `BSTR`, let me know if you want anything else.

**Pull request merged**
