### PR TITLE
Added support for SVG files. 

### PR DESCRIPTION
**Pull request by MasterSkriptor**
This is a feature pull request. It adds support for svg files. The BSSvg component can render svg markup both inline or loaded from a file.

The BSSvg component loads an svg file and injects the markup directly into the html, which allows for custom animations from the sites css files.

While it is not strictly associated with bootstrap, it is (IMHO) a powerful tool for adding dynamic animations to a blazor site. It can greatly augment the carousel, as well as svg's used as the NavBrand.

I also updated the BSCarouselItem to something much cleaner. Currently using a SVG in the BSCarouselItem stops you from being able to use the BSCarouselCaption while using SVG's. I fixed that in this pull request.

I could have coded the SvgLoader into the BSSvg so that users would not have to register the service in order to use the component. I opted to make the service for two reasons: 

- It better adheres to SRP, and in the event that we add tests, is much easier to mock.

- It gives the user more control over using the service or not, and does not load the service if the user never wishes to use it.

This pull request also adds the documentation for the component to the website, with detailed instructions for setting up the service and using the component. The Carousel section was also updated to reflect the changes of this pull request.

I made a lot of assumptions in the design of this component, but I am fully willing to update it if it does not adhere to your design flow.

### CODE REVIEW

**Comment by chanan** [comment]
Thanks @MasterSkriptor 

This is as good a place as any to have this conversation @jbomhold3 

What do you guys think of collapsing all the extensions projects into one projects with the individual projects as folders. That way we can release it on nuget as one BlazorStrap.extensions instead of each one having its own nuget? Maybe there is a way to combine the dlls into one I don’t know how though.

**Comment by MasterSkriptor** [comment]
Consider this, fluent validations has a dependency on the FluentValidation package. If we combine them all, someone who is using DataAnnotations is forced to include the package for FluentValidation when they may only be after the DataComponents (for example.) What are the ramifications of this on client side blazor when the client downloads the dlls?

My thoughts on this are that we are kind of stuck between a rock and a hard place. We must balance user integration (namely how easy it is to set up) with performance and support. It is much easier for the user to setup and manage with all the extensions in one place, but it invariably causes a much more bloated package than the separation of concerns.

My understanding is that you can use .nuspec files to include multiple extensions in one nuget package while also having packages to keep them seperate. I have never done this however, and think it would add a lot of overhead for setting up continuous integration.

If BlazorStrap is meant to be fully supported framework for blazor, and evolves into something that gets a lot of use, support is also an important consideration. It would be in the best interest of the support group to limit the lines of code to support for the majority of users.

I had this debate with myself developing this particular component. The BSSvg component depends on the SvgLoader service. I do not like the fact that the core of blazorstrap has a dependency on a service that is essentially an extension. Also the BSSvg component could work fine without the extension if you use inline markup, but because the service is injected it requires the extension. At some point I intend to address this issue by moving the Src attribute into an extension of the BSSvg class itself, so that when you install the SvgLoader extension, it adds the Src parameter to the BSSvg component.

I agree with you @chanan one hundred percent. Now is the time to consider this, before BlazorStrap grows into something that is widely used. It is important that we as contributors to this project stay inside the boundaries of your overall design, and avoid the unintended bloating of the project a lot of extensions may bring to the table in terms of use and support.

**Comment by jbomhold3** [comment]
We could just set up a CD pipeline for them in the other project that way it takes care of keeping the NuGet package up to date for us.  Then do a meta-package for people that want all the extensions. I don't think having one big package is the best route for reasons already stated but giving them the option works nicely. I have finally gotten good at pipelines so don't mind setting it up. So anything in the Release / Perrelease branch gets published automatically

**Comment by chanan** [comment]
@jbomhold3 That would be awesome!

**Comment by chanan** [comment]
@jbomhold3 Will you be able to add pipeline support soon?

**Comment by jbomhold3** [comment]
Whenever your ready when you can hit me up on skype

**Comment by chanan** [comment]
@jbomhold3 Tomorrow? I am beat tonight. Need some rest

**Pull request merged**
