### PR TITLE
Preview6

### LINKED ISSUE #58: Support Blazor Preview 6
Preview 6 added quite a few breaking changes.

Blog: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

### PR DESCRIPTION
**Pull request by chucker**
Should fix #58

### CODE REVIEW

**Comment by chanan** [comment]
Awesome! I will take a look at this tonight!

**Comment by chucker** [comment]
A few notes:

* I've resorted to going back to `@functions` for the Sample project for now, because even on VS 2019.2 p 2.2, `@code` caused all kinds of haywire (but _only_ in the Sample project?!). See 
`c0aa925`. In a later preview, that commit should be reverted.
* I've tested basic stuff. JavaScript works (Tooltips, Popovers).

**Comment by chanan** [comment]
Weird about the @code. Will, keep an eye on it.

**Comment by chanan** [comment]
@chucker I fixed Alert - Changed the events from action to EventCallback and put @code in the page instead of @functions.

Could you grab the last commit: https://github.com/chanan/BlazorStrap/commit/354a68c8fa04077a6b21e22e7e2745aeb66b4412 and check /alerts make sure you get no errors in the console as well as click the dismiss X on the last alert and see you get the output in the console please?

**Comment by chanan** [comment]
Alert works (I think) but the rest don't seem to work, opening an issue in aspnet repo

**Pull request merged**
