### PR TITLE
Added child modal support to prevent scrolling issues in parent modal

### PR DESCRIPTION
**Pull request by alexandredsimoes**
In some LOB Applications, child modal is very common scenario. However when child modal is closed, the page scroll is lost leaving the parent modal without scroll.

### CODE REVIEW

**Comment by jbomhold3** [comment]
This looks good though. It might be better to pass down a parameter of new GUID from all models so each and every model below can know if it has a parent. Or even pass it's self down so the child model can access the parent model. If it's has a parent don't remove the body tag if now remove it.

**Comment by jbomhold3** [comment]
This would also prevent the user from having to do anything extra. Just nest as normal.

**Comment by jbomhold3** [comment]
@alexandredsimoes do you want to make the changes?

**Comment by alexandredsimoes** [comment]
No changes.

**Comment by chanan** [comment]
@jbomhold3 and @alexandredsimoes I am unclear where we are on this issue. @jbomhold3 says we should pass down a GUID - Is that change going to happen in this PR?

**Pull request closed without merging**
