### PR TITLE
Prevent interaction with hidden tooltips. Closes #29

### LINKED ISSUE #29: Links in tooltips are clickable when invisible
When tooltip disappears, the invisible link is still clickable if you hover above its location. 
Is there any better way of hiding the tooltips?

Reproduce with:

```
<Tooltip Target="div1" Placement="Placement.Bottom">
Text here. Text here. Text here. Text here.<br />
Text here. Text here. Text here. Text here.<br />
<a target="_blank" href="https://www.github.com/">Read more</a>.
</Tooltip>

```

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- this adds the component scoped styles allowign to fine tune component
UI details after BS styles are loaded
- swallow pointer events while tooltips are hidden

Thanks!

### CODE REVIEW

**Comment by chanan** [comment]
To use this, the developer would need to reference the styles.css from the html file. Is there we can do this without that?
If not, we should update the docs as well

**Comment by peterblazejewicz** [comment]
> To use this, the developer would need to reference the styles.css from the html file. Is there we can do this without that?

Nope, imo. The default template for component/library ships with this:

```xml
<ItemGroup>
    <!-- .js/.css files will be referenced via <script>/<link> tags; other content files will just be included in the app's 'dist' directory without any tags referencing them -->
    <EmbeddedResource Include="content\**\*.js" LogicalName="blazor:js:%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="content\**\*.css" LogicalName="blazor:css:%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="content\**" Exclude="**\*.js;**\*.css" LogicalName="blazor:file:%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
```
image

https://dzone.com/articles/building-blazor-shared-components

**Comment by peterblazejewicz** [comment]
I'm closing this in favour of other solution

**Comment by chanan** [comment]
For SSB they would, but they already need to include balzorStap.js and popper.min.js - so its all good

**Pull request closed without merging**
