### PR TITLE
Add ability to Focus on a BSInput or BSBasicInput

### PR DESCRIPTION
**Pull request by kiasyn**
I keep needing to focus on inputs (eg, after opening a modal, or showing an input after clicking a button) so I have exposed this via BlazorStrapInterop.

If this is not something you want to support (since it has the JS dependency) could we look at exposing ElementReference so that I could implement the focus on my end?

Cheers

### CODE REVIEW

**Comment by jbomhold3** [comment]
Looks good to me.

**Comment by ruthequip** [comment]
I have upgraded to this prerelease but BSInput does not have a Focus() function available. How do we use this function, or am I doing something wrong? I've used @ref="myInput" and then in my method that opens a modal, I'm trying to call "myInput.Focus()" but it's not there to call

**Comment by ruthequip** [comment]
> I have upgraded to this prerelease but BSInput does not have a Focus() function available. How do we use this function, or am I doing something wrong? I've used @ref="myInput" and then in my method that opens a modal, I'm trying to call "myInput.Focus()" but it's not there to call

Figured it out. Nuget is not pulling the correct source. If I download the source from here and build, it's there.

**Comment by ruthequip** [comment]
> > I have upgraded to this prerelease but BSInput does not have a Focus() function available. How do we use this function, or am I doing something wrong? I've used @ref="myInput" and then in my method that opens a modal, I'm trying to call "myInput.Focus()" but it's not there to call
> 
> Figured it out. Nuget is not pulling the correct source. If I download the source from here and build, it's there.

Further findings. So I was trying to focus an input when a modal opens. I noticed, at least in this release, Modal never invokes it's "ShownEvent" callback. I had planned to use that callback to focus the input once the modal was up, doing so before failed to focus the input. The "Show" event, however is being invoked, but it happens so fast that it wasn't working. I went in right before the ShowEvent.InvokeAsync line and added another 200 ms delay, seems to work so far, at least for my purposes

**Comment by timbze** [comment]
.NET 5.0 also adds `FocusAsync()` for ElementReference. See [this](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-8/#set-ui-focus-in-blazor-apps)

**Comment by chanan** [comment]
Might be a good idea to add that to the input components as a method directly on the component that gets the ref and calls it, instead of making the end developer doing that - When we move to .net 5

**Pull request merged**
