### PR TITLE
C# 8 patterns, coding style, property simplify

### PR DESCRIPTION
**Pull request by hez2010**
1. Use C# 8 pattern matching expressions to reduce redundant code.
2. Fix coding style and indents.
3. Simplify single line properties and methods access.

### CODE REVIEW

**Comment by chanan** [comment]
Thanks for this PR! The => Switch syntax is really good.

Will merge and release tonight

**Comment by hez2010** [comment]
@chanan
I've upgrade TargetFramework to .NET Standard 2.1

**Comment by chanan** [comment]
@hez2010 Why the change to 2.1? Won't leaving it 2.0 be better?

**Comment by hez2010** [comment]
2.0 is still okay and compatible with C# 8 syntax. However, since blazor now only support .net core 3.0, I think it's okay to move to .net standard 2.1.  
With .net standard 2.1, the project may benefit from the new `Span<T>` and `Memory<T>` in the future.

**Comment by chanan** [comment]
I just wonder if any potential Blazor developers might use 2.0 and by changing to 2.1 we limit the audience of developers?

**Comment by hez2010** [comment]
Oh I forgot this consideration. I've downgraded it to 2.0 :P

**Comment by chanan** [comment]
Yo be clear, I was just asking, I dont know the correct answer here :) But I guess if we want to update to 2.1 later we always can

**Comment by chanan** [comment]
Working on the merge now

**Comment by chanan** [comment]
There is a merge conflict now, can you fix that on your side? The Github web merge conflict is not very useful.

I am going to open an issue asking for comments from people that contribute to BlazorStrap about how we should go forward with contributions in a sane way, merging to Master worked when the project was smaller...

**Comment by hez2010** [comment]
Merge issue fixed.

**Comment by chucker** [comment]
It should remain at 2.0 unless it actually _uses_ 2.1 features.

That said, I don't think there's a scenario where you use Blazor from a runtime that doesn't support 2.1, so that may be moot.

**Pull request merged**
