### PR TITLE
Added: Show/Hide/Toggle to Collapse, Dropdowns, Navbar, Popovers.

### PR DESCRIPTION
**Pull request by jbomhold3**
Blocked the ability to use Boolean IsOpen and @ref show/hide/toggle together. Setting bool from a
child is overwritten by the parent. As this is intended functionality by manually controlling IsOpen so these cannot be used together.

### CODE REVIEW

**Comment by chanan** [comment]
There was no way to mix IsOpen with the new format?

**Comment by jbomhold3** [comment]
IsOpen the parent is controlling the child.   @Ref the child is controlling its self.    So what's happening is toggle false true than false again when the parent is called. I don't see this being an issue. If you opt into manually controlling things. You're going to be responsible for controlling it. The ladder controls everything for you. I'm sure I could make it place nice. However, I don't see where it would be any good doing that. It does not break anything having them both in place. But it will toss an exception to prevent silly behavior.

**Comment by jbomhold3** [comment]
plus side in doing this. Nothing that toggles requires a parent bool anymore

**Comment by jbomhold3** [comment]
Isopenchnaged can be subscribed to. To update the parent. I could remove the expectation but I think it will create more of a headache then needed. Very much on the side of if you want manual control you own it completely

**Comment by chanan** [comment]
Sounds good.

I am right now in the middle of updating BlazorStyled. I will grab this PR either later today or over the weekend.

**Comment by jbomhold3** [comment]
That's fine I want to add the onfocusout to this pr anyways. Just was wondering you preference  on allowing users to mix both and likely forget to handle the event

**Comment by chanan** [comment]
I think your approach sounds fine. Once I grab the PR, I will test it out in the pages and see how it works (seeing is easier than reading)

**Comment by jbomhold3** [comment]
FocusOut works. If you do a manual toggle you will have to add @onfocusout="@YourCloseFunc" to the NavItem component tag or Dropdown component tag

**Pull request merged**
